# Generated by Django 3.1.7 on 2021-05-01 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookiernesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('secret_number', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GraphicDesigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='new_book_version',
        ),
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='book_designed',
            field=models.FileField(blank=True, null=True, upload_to='book_designed'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_to_design',
            field=models.FileField(blank=True, null=True, upload_to='book_to_design'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.CharField(blank=True, choices=[('presented', 'Presentat'), ('revised', 'Revisat'), ('modifying', 'Modificant'), ('accepted', 'Aceptat'), ('rejected', 'Rebutjat'), ('published', 'Publicat'), ('designing', 'Maquetacio'), ('new_version', 'New Version')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('writer', 'Escritor'), ('editor', 'Editor'), ('main_editor', 'Escriptor principal'), ('main_graphic_designer', 'Main Graphic Designer'), ('graphic_designer', 'Graphic Designer'), ('it', 'IT'), ('subscribed_reader', 'Lector Subscrit')], default='writer', max_length=255),
        ),
        migrations.CreateModel(
            name='SubscribedReader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='BookiernesApp.creditcard')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Subscribed_reader_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagePetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_received', models.DateField()),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='editor_petition', to='BookiernesApp.editor')),
                ('graphic_designer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='graphic_designer_petition', to='BookiernesApp.graphicdesigner')),
                ('images_attached', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='BookiernesApp.image')),
            ],
        ),
        migrations.AddField(
            model_name='graphicdesigner',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graphic_designer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='BookiernesApp.image'),
        ),
        migrations.AddField(
            model_name='book',
            name='designer_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='designer_books_assigned', to='BookiernesApp.graphicdesigner'),
        ),
    ]
