# Generated by Django 3.1.7 on 2021-04-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookiernesApp', '0002_auto_20210413_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='path_profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='profile_photo'),
        ),
    ]
