# Generated by Django 3.1.7 on 2021-05-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookiernesApp', '0002_auto_20210501_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepetition',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
    ]
