# Generated by Django 3.1.7 on 2021-05-08 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookiernesApp', '0003_auto_20210508_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepetition',
            name='images_attached',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attached_images', to='BookiernesApp.image'),
        ),
    ]
