# Generated by Django 3.1.7 on 2021-04-11 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookiernesApp', '0004_auto_20210401_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='new_book_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BookiernesApp.book'),
        ),
    ]
