# Generated by Django 3.1.7 on 2021-04-11 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookiernesApp', '0004_auto_20210401_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books_assigned', to='BookiernesApp.editor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='BookiernesApp.writer'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.CharField(blank=True, choices=[('presented', 'Presentat'), ('revised', 'Revisat'), ('modifying', 'Modificant'), ('accepted', 'Aceptat'), ('rejected', 'Rebutjat'), ('published', 'Publicat')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='main_editor_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to='book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books_themes', to='BookiernesApp.theme'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
