# Generated by Django 3.1.7 on 2021-05-08 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookiernesApp', '0004_auto_20210509_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepetition',
            name='images_attached',
        ),
        migrations.AddField(
            model_name='image',
            name='petition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attached_images', to='BookiernesApp.imagepetition'),
        ),
    ]
