# Generated by Django 3.1.7 on 2021-04-11 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookiernesApp', '0007_auto_20210411_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
